// Bundles the geometry worker into src/worker.gen.js (inlined into the app
// as text -> Blob URL, because bun cannot bundle `new Worker(new URL(...))`).
// The manifold WASM binary is embedded as base64 first: a Blob-URL worker
// has no usable base URL and the dev server does not serve emitted assets.
const wasm = await Bun.file('node_modules/manifold-3d/manifold.wasm').arrayBuffer();
const b64 = Buffer.from(wasm).toString('base64');
await Bun.write('src/manifold-wasm.ts',
  `// generated by scripts/build-worker.ts — do not edit\nexport default '${b64}';\n`);

const result = await Bun.build({
  entrypoints: ['src/worker.ts'],
  target: 'browser',
  format: 'esm',
  minify: true,
});
if (!result.success) {
  console.error(result.logs.join('\n'));
  process.exit(1);
}
let code = await result.outputs[0]!.text();
// the emscripten glue eagerly builds `new URL('manifold.wasm', import.meta.url)`
// even when wasmBinary is supplied — and a blob: base URL makes that throw.
// The URL is never fetched, so any valid absolute base will do.
code = code.replaceAll('import.meta.url', '"file:///"');
await Bun.write('src/worker.gen.js', code);
console.log('worker.gen.js bundled (wasm embedded)');
